name: Wrangler Test NPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Wrangler Install
      run: npm i @cloudflare/wrangler -g
      
    - name: Wrangler Login
      run: wrangler login
      
    - name: First Jobs
      run: wrangler generate my-app https://github.com/cloudflare/worker-template

